name: blind_mans_bluff
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  vibrate:
  flutter_tts: ^1.2.7
  cupertino_icons: ^0.1.2
  path_provider: ^1.6.14
  shared_preferences: ^0.5.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  camera: 0.5.8+5
  tflite: 1.1.1


flutter:
  uses-material-design: true
  assets:
    - assets/yolov2_tiny.tflite
    - assets/yolov2_tiny.txt
    - assets/History.txt

